## Reference: https://github.com/amannn/action-semantic-pull-request
---
name: "Lint PR Title"
on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
permissions:
  contents: read
jobs:
  main:
    permissions:
      contents: read
      pull-requests: read
      statuses: write
    uses: github-community-projects/ospo-reusable-workflows/.github/workflows/pr-title.yaml@7fc8753b3666b929250bb6241ce4b2d35f316a11 # v1.2.1
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
